name: "release"
on:
  workflow_dispatch:
    inputs:
      newVersion:
        description: "New Version"
        required: true
        type: string
jobs:
  release:
    permissions:
      contents: write
    env:
      PACKED_JS_PATH: "dist/index.js"
    runs-on: ubuntu-latest
    steps:
      - name: Check Semver
        run: |
          if ! [[ '${{ inputs.newVersion }}' =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo Invalid semversion input: ${{ inputs.newVersion }}
            exit 1
          fi
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org/
          node-version: 20.x
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Check packed js changes
        id: packedJsStatus
        run: echo "changes=$(git status ${{ env.PACKED_JS_PATH }} --porcelain)" >> "$GITHUB_OUTPUT"
      - name: test
        if: steps.packedJsStatus.outputs.changes
        run: npm run test
      - name: Commit packed js
        id: commitPackedJs
        if: steps.packedJsStatus.outputs.changes
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add ${{ env.PACKED_JS_PATH }}
          git add dist/licenses.txt
          git add dist/package.json
          git commit -m "build: new version pack ${{ inputs.newVersion }}"
      - name: Push packed js
        if: steps.commitPackedJs.outcome == 'success'
        run: |
          git tag -m 'new version' '${{ inputs.newVersion }}' && git push --follow-tags
