name: "release"
on:
  workflow_dispatch:
    inputs:
      version:
        description: "next action version"
        required: true
        type: string
jobs:
  release:
    permissions:
      contents: write
    env:
      PACKED_JS_PATH: "dist/main.js"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org/
          node-version: 20.x
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Check packed js changes
        id: packedJsStatus
        run: echo ::set-output name=changes::$(git status ${{ env.PACKED_JS_PATH }} --porcelain)
      - name: test
        if: steps.packedJsStatus.outputs.changes
        run: npm run test
      - name: Commit packed js
        id: commitPackedJs
        if: steps.packedJsStatus.outputs.changes
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add ${{ env.PACKED_JS_PATH }}
          git commit -m "Pack with dependencies to ${{ env.PACKED_JS_PATH }}"
      - name: Push packed js
        if: steps.commitPackedJs.outcome == 'success'
        run: |
          git tag ${{ github.event.inputs.newVersion }} && git push --follow-tags
